name 'dwerder-grafana'
version '1.0.0'
source 'git clone https://github.com/echocat/puppet-grafana.git'
author 'Daniel Werdermann'
license 'Mozilla Public License Version 2.0'
summary 'Grafana module'
description 'This module installs and configures Grafana to be used with graphite and co.'
project_page 'https://github.com/echocat/puppet-grafana'

dependency   'puppetlabs/stdlib', '>= 3.2.0'
